builds:
  - main: ./cmd/goad/
    binary: goad
    id: goad-cli

    env:
      - CGO_ENABLED=0

    goos: [windows,linux,darwin]
    goarch: [amd64,386,arm,arm64]
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

    flags:
      - -trimpath

archives:
  - format: zip
    id: goad
    builds: [goad-cli]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^MERGE'
      - "{{ .Tag }}"
