name: 🔨 Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Check out code
        uses: actions/checkout@v3

      - name: Go Mod hygiene
        run: |
          go clean -modcache
          go mod tidy
      
      - name: Build
        run: go build .
        working-directory: cmd/goad/

      - name: Test
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: go test ./...  

# TODO: race tests
